import {
  ManagedUser,
  Customer,
  Product,
  Order,
  AuditLog,
  AppNotification,
  DashboardMetrics,
  RevenueMetric,
  TrafficSource,
} from '../types';

export const initialDashboardMetrics: DashboardMetrics = {
  totalRevenue: 248950,
  revenueGrowth: 14.2,
  activeSubscriptions: 1420,
  subscriptionsGrowth: 8.5,
  activeUsers: 18450,
  usersGrowth: 22.4,
  churnRate: 1.8,
  churnGrowth: -0.4,
};

export const initialRevenueMetrics: RevenueMetric[] = [
  { month: 'Jan', revenue: 18500, expenses: 9200, profit: 9300 },
  { month: 'Feb', revenue: 21200, expenses: 9800, profit: 11400 },
  { month: 'Mar', revenue: 24800, expenses: 10400, profit: 14400 },
  { month: 'Apr', revenue: 23500, expenses: 10100, profit: 13400 },
  { month: 'May', revenue: 28900, expenses: 11500, profit: 17400 },
  { month: 'Jun', revenue: 32400, expenses: 12100, profit: 20300 },
  { month: 'Jul', revenue: 36800, expenses: 13000, profit: 23800 },
  { month: 'Aug', revenue: 41200, expenses: 13800, profit: 27400 },
];

export const initialTrafficSources: TrafficSource[] = [
  { source: 'Direct Search', users: 8420, conversionRate: 4.8, color: '#6366f1' },
  { source: 'Organic SEO', users: 5120, conversionRate: 3.2, color: '#3b82f6' },
  { source: 'Partner Referrals', users: 3240, conversionRate: 6.5, color: '#10b981' },
  { source: 'Social Media', users: 1670, conversionRate: 2.1, color: '#f59e0b' },
];

export const initialManagedUsers: ManagedUser[] = [
  {
    id: 'usr-1',
    name: 'Rahul Jaggi',
    email: 'rahul.jaggi@enterprise.io',
    role: 'Super Admin',
    status: 'Active',
    department: 'Executive Leadership',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    lastLogin: 'Just now',
    createdAt: '2024-01-15',
  },
  {
    id: 'usr-2',
    name: 'Sarah Connor',
    email: 'sarah.c@enterprise.io',
    role: 'Admin',
    status: 'Active',
    department: 'Engineering',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    lastLogin: '2 hours ago',
    createdAt: '2024-02-01',
  },
  {
    id: 'usr-3',
    name: 'Marcus Vance',
    email: 'marcus.vance@enterprise.io',
    role: 'Manager',
    status: 'Active',
    department: 'Product Strategy',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    lastLogin: '1 day ago',
    createdAt: '2024-02-12',
  },
  {
    id: 'usr-4',
    name: 'Elena Rostova',
    email: 'elena.r@enterprise.io',
    role: 'Analyst',
    status: 'Active',
    department: 'Data & Analytics',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    lastLogin: '3 hours ago',
    createdAt: '2024-03-05',
  },
  {
    id: 'usr-5',
    name: 'David Kim',
    email: 'david.k@enterprise.io',
    role: 'Support',
    status: 'Inactive',
    department: 'Customer Success',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    lastLogin: '5 days ago',
    createdAt: '2024-03-20',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Acme Global Corp',
    company: 'Acme Global',
    email: 'billing@acmeglobal.com',
    plan: 'Enterprise',
    status: 'Active',
    totalSpent: 48000,
    ordersCount: 12,
    createdAt: '2024-01-10',
  },
  {
    id: 'cust-2',
    name: 'Stark Industries',
    company: 'Stark Tech',
    email: 'contact@stark.io',
    plan: 'Enterprise',
    status: 'Active',
    totalSpent: 96000,
    ordersCount: 24,
    createdAt: '2024-01-20',
  },
  {
    id: 'cust-3',
    name: 'Nebula AI Systems',
    company: 'Nebula AI',
    email: 'finance@nebula.ai',
    plan: 'Professional',
    status: 'Active',
    totalSpent: 14500,
    ordersCount: 6,
    createdAt: '2024-02-15',
  },
  {
    id: 'cust-4',
    name: 'Cyberdyne Labs',
    company: 'Cyberdyne',
    email: 'ops@cyberdyne.com',
    plan: 'Starter',
    status: 'Pending',
    totalSpent: 2400,
    ordersCount: 2,
    createdAt: '2024-03-01',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Enterprise Cloud Core',
    sku: 'SKU-CLD-100',
    category: 'Cloud Resource',
    price: 2499,
    stock: 45,
    status: 'In Stock',
    rating: 4.9,
    salesCount: 320,
    createdAt: '2024-01-01',
  },
  {
    id: 'prod-2',
    name: 'AI Analytics Engine License',
    sku: 'SKU-AI-500',
    category: 'API License',
    price: 1299,
    stock: 12,
    status: 'Low Stock',
    rating: 4.8,
    salesCount: 180,
    createdAt: '2024-01-15',
  },
  {
    id: 'prod-3',
    name: 'Zero-Trust Security Suite',
    sku: 'SKU-SEC-300',
    category: 'Software',
    price: 3499,
    stock: 80,
    status: 'In Stock',
    rating: 4.95,
    salesCount: 410,
    createdAt: '2024-02-01',
  },
  {
    id: 'prod-4',
    name: 'Dedicated Support Package',
    sku: 'SKU-SUP-050',
    category: 'Add-on',
    price: 499,
    stock: 0,
    status: 'Out of Stock',
    rating: 4.6,
    salesCount: 520,
    createdAt: '2024-02-10',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'ORD-2024-8841',
    customerName: 'Acme Global Corp',
    customerEmail: 'billing@acmeglobal.com',
    amount: 4998,
    status: 'Completed',
    paymentMethod: 'Wire Transfer',
    items: [
      { productId: 'prod-1', productName: 'Enterprise Cloud Core', quantity: 2, unitPrice: 2499 },
    ],
    createdAt: '2026-07-19 14:32',
  },
  {
    id: 'ord-102',
    orderNumber: 'ORD-2024-8842',
    customerName: 'Stark Industries',
    customerEmail: 'contact@stark.io',
    amount: 3499,
    status: 'Processing',
    paymentMethod: 'Credit Card',
    items: [
      { productId: 'prod-3', productName: 'Zero-Trust Security Suite', quantity: 1, unitPrice: 3499 },
    ],
    createdAt: '2026-07-20 09:15',
  },
  {
    id: 'ord-103',
    orderNumber: 'ORD-2024-8843',
    customerName: 'Nebula AI Systems',
    customerEmail: 'finance@nebula.ai',
    amount: 1299,
    status: 'Pending',
    paymentMethod: 'ACH',
    items: [
      { productId: 'prod-2', productName: 'AI Analytics Engine License', quantity: 1, unitPrice: 1299 },
    ],
    createdAt: '2026-07-20 11:40',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'audit-1',
    user: 'Rahul Jaggi',
    email: 'rahul.jaggi@enterprise.io',
    action: 'USER_LOGIN_SUCCESS',
    category: 'Security',
    ipAddress: '192.168.1.104',
    status: 'Success',
    timestamp: '2026-07-20 20:15:02',
  },
  {
    id: 'audit-2',
    user: 'Sarah Connor',
    email: 'sarah.c@enterprise.io',
    action: 'ROLE_PERMISSION_MODIFIED',
    category: 'User Management',
    ipAddress: '10.0.4.88',
    status: 'Success',
    timestamp: '2026-07-20 18:22:11',
  },
  {
    id: 'audit-3',
    user: 'System Bot',
    email: 'system@enterprise.io',
    action: 'FAILED_API_AUTHENTICATION',
    category: 'Security',
    ipAddress: '172.16.0.42',
    status: 'Warning',
    timestamp: '2026-07-20 16:04:45',
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'High Security Alert',
    message: 'New API Key created for production deployment cluster.',
    type: 'warning',
    isRead: false,
    timestamp: '10 mins ago',
  },
  {
    id: 'notif-2',
    title: 'New Enterprise Customer',
    message: 'Stark Industries upgraded subscription plan to Enterprise level.',
    type: 'success',
    isRead: false,
    timestamp: '1 hour ago',
  },
  {
    id: 'notif-3',
    title: 'Automated Backup Completed',
    message: 'PostgreSQL database snapshot saved safely to S3 primary region.',
    type: 'info',
    isRead: true,
    timestamp: '3 hours ago',
  },
];
